### ISSUE TITLE
Tracking Issue: Compile-time Configuration Framework

### ISSUE THREAD

**Issue by Rain336** [Microdragon/Kernel#5]
Tracking issue for #3 

- [x] Implement the `config!` proc-macro function (#6)
- [x] Implement the `#[config::cfg(...)]` proc-macro function (#7)
- [x] Implement the `#[config::cfg_attr(..., ...)]` proc-macro function (#7)
- [ ] Implement CLI tool - Line Args Mode
- [ ] Implement CLI tool - Terminal UI Mode

**Comment by Rain336** [comment]
Will put this on hold for now, I started working on the [CLI tool](https://github.com/Rain336/Kernel/tree/configuration-cli) but I now kinda question it's usability. The Terminal UI tool would be nice though. Am generally not that confidant in the current state of the configuration framework and might need to go back to the drawing board on it a bit.
